version: "3.9"
services:
  frontend:
    container_name: nginx-frontend-app
    image: dssaregistry.azurecr.io/navigator/front:latest
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443

  backend:
    container_name: node-app
    image: dssaregistry.azurecr.io/navigator/back:latest
    restart: always
    env_file:
      - .env
