version: "3.9"
services:
  frontend:
    image: dssaregistry.azurecr.io/navigator/front:latest
    restart: always
    build:
      context: ./client/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443

  backend:
    image: dssaregistry.azurecr.io/navigator/back:latest
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    env_file:
      - .env
