version: "3.9"
services:
  frontend:
    container_name: nginx-frontend-app
    image: navigator_frontend
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443

  backend:
    container_name: node-app
    image: navigator_backend
    restart: always
    env_file:
      - .env
